# Generated by Django 4.0.4 on 2022-04-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_member_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
